title: Tincidunt non
catchphrase: Proin aliquam, eros eget vulputate
job: Duis suscipit varius null
jobtitle: Duis suscipit
copyright: Copyright © 2017 - Tincidunt Non. All Rights Reserved.
thanks: Proin aliquam, eros eget vulputate!
picture: /assets/brand/profile.jpg

social:
  instagram: itzegomind
  email: itzegomind@gmail.com
  tumblr: egomind
  facebook: itzegomind
  pinterest: ischiaffini
